# Generated by Django 5.1 on 2024-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_user_fname_user_date_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
