# Generated by Django 5.1 on 2024-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applicationforms_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforms',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
