# Generated by Django 5.1.1 on 2024-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applicationforms_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforms',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
