# Generated by Django 5.1.1 on 2024-09-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customuser_is_admin_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservideos',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserImages',
        ),
        migrations.DeleteModel(
            name='UserVideos',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserDocuments',
        ),
    ]
