# Generated by Django 5.1.1 on 2024-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_userimages_user_remove_uservideos_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthday', models.DateField()),
                ('phone_number1', models.CharField(max_length=30)),
                ('phone_number2', models.CharField(blank=True, max_length=30, null=True)),
                ('Driving_license_id', models.CharField(max_length=30)),
                ('driving_license_expiry_date', models.DateField()),
                ('passport_id', models.CharField(max_length=30)),
                ('passport_expiry_date', models.DateField()),
                ('home_address', models.CharField(max_length=100)),
                ('work_office_address', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('image_uploaded_at', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('video_uploaded_at', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('uploaded_at', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
        ),
    ]
