# Generated by Django 5.1.1 on 2024-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
