# Generated by Django 5.1.1 on 2024-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_users_password1_users_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Driving_license_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='passport_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
