# Generated by Django 5.1.1 on 2024-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_users_passport_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='driving_license_expiry_date',
            field=models.CharField(max_length=100),
        ),
    ]
