# Generated by Django 5.1.1 on 2024-09-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_users_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passport_expiry_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
