# Generated by Django 5.1.1 on 2024-09-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_users_passport_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
